apiVersion: v1
kind: Pod
metadata:
  namespace: presto
  name: presto-cli
spec:
#  volumes:
#    - name: shared-vol
#      persistentVolumeClaim:
#        claimName: data-client-share
  containers:
  - name: presto-cli
    image: "olegsimanov/prestosql-cli:330"
    # Just spin & wait forever
    command: [ "tail", "-f", "/dev/null" ]
    # Configure a mountpoint for the volume we defined above
#    volumeMounts:
#      - name: shared-vol
#        mountPath: /data
