---
apiVersion: v1
kind: Service
metadata:
  name: presto
  namespace: presto
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: presto-coordinator


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-coordinator
  namespace: presto
spec:
  selector:
    matchLabels:
      app: presto-coordinator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: presto-coordinator
    spec:
      containers:
      - name: presto-coordinator
        image: olegsimanov/prestosql-server:330
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: presto-etc-vol
          mountPath: /opt/presto-server/etc/config.properties
          subPath: config.properties.coordinator
        - name: presto-etc-vol
          mountPath: /opt/presto-server/etc/jvm.config
          subPath: jvm.config.coordinator
        - name: presto-catalog-vol
          subPath: mongodb.properties
          mountPath: /opt/presto-server/etc/catalog/mongodb.properties
        imagePullPolicy: Always
      volumes:
        - name: presto-etc-vol
          configMap:
            name: presto-etc
        - name: presto-catalog-vol
          configMap:
            name: presto-catalog


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-worker
  namespace: presto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presto-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: presto-worker
    spec:
      containers:
      - name: presto-worker
        image: olegsimanov/prestosql-server:330
        volumeMounts:
        - name: presto-etc-vol
          mountPath: /opt/presto-server/etc/config.properties
          subPath: config.properties.worker
        - name: presto-etc-vol
          mountPath: /opt/presto-server/etc/jvm.config
          subPath: jvm.config.worker
        - name: presto-catalog-vol
          subPath: mongodb.properties
          mountPath: /opt/presto-server/etc/catalog/mongodb.properties
        imagePullPolicy: Always
      volumes:
        - name: presto-etc-vol
          configMap:
            name: presto-etc
        - name: presto-catalog-vol
          configMap:
            name: presto-catalog
